package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(plugin *protogen.Plugin) error {

		for _, f := range plugin.Files {
			if !f.Generate {
				continue
			}

			fInfo := newFileInfo(f)

			generateFile(plugin, fInfo)

		}

		return nil

	})
}

func generateFile(plugin *protogen.Plugin, fInfo *fileInfo) *fileInfo {

	fInfo.discoverFile()
	fInfo.importNeeds.discoverFiles(plugin.Files)

	if len(fInfo.messages) == 0 {
		return fInfo
	}

	filename := fInfo.file.GeneratedFilenamePrefix + "_terraform.pb.go"

	gen := plugin.NewGeneratedFile(filename, fInfo.file.GoImportPath)

	t := tab(0)

	t.P(gen, "// Code generated by protoc-gen-terraform. DO NOT EDIT.")
	gen.P()

	t.P(gen, "package ", fInfo.file.GoPackageName)
	gen.P()

	fInfo.importNeeds.writeFile(t, gen)
	gen.P()

	fInfo.writeFunctions(t, gen)
	gen.P()

	return fInfo

}
